### ISSUE TITLE
Implémentation concrète

### ISSUE THREAD

**Issue by ScreamZ** [gmorel/StateWorkflowBundle#1]
Salut,

j'aime bien mais aurais-tu une implémentation avec des entités persistantes ?

**Comment by gmorel** [comment]
En gros tu tu n'aurais qu'à persister le résultat de [StateInterface::getKey()](https://github.com/gmorel/Symfony2---Design-Pattern-Example---State/blob/master/Acme/DemoBundle/State/StateInterface.php#L37-37).

Par exemple si tu as le cas d'une Entity Doctrine `Quote` (Devis) qui contient plusieurs status (Draft, ..., Completed) ça donnerait ça :

![state_design_pattern 1](https://cloud.githubusercontent.com/assets/2279794/6770688/1ad60698-d0c8-11e4-8853-ee1bbdca21ed.png)

Ta couche de persistance reste la même, tu vas juste devoir implémenter [HasStateInterface](https://github.com/gmorel/Symfony2---Design-Pattern-Example---State/blob/master/Acme/DemoBundle/State/HasStateInterface.php#L13-13). Qui va te permettre de ne persister que la `key` du status (String ou int).

``` php
// ******************************
// Init State Engine
// ******************************
$stateDraft = new State\Dfraft();
$stateX = new State\X();
$stateCompleted = new State\Completed();

$stateManager = new StateManager($stateDraft->getKey());

// ******************************
// Entity Initialisation
// ******************************
$entityQuote = new Entity\Quote(...);
$stateManager->initState($entityQuote);

// Assert
$currentState = $stateManager->getCurrentState($entityQuote);
($currentState instanceof State\Dfraft); // return true
$entityManager->persist($entityQuote);

// ******************************
// Transition to State\Completed
// ******************************
$stateManager->changeState($entityQuote, $stateCompleted);
// StateCompleted is taking care of managing the draft -> completed transistion
$entityManager->persist($entityQuote);

// ******************************
// Load Entity
// ******************************
$refreshedQuote = $quoteRepository->find(1);

$currentState = $stateManager->getCurrentState($refreshedQuote);
($currentState instanceof State\Completed); // return true
```

Désolé pour le délais.
Merci pour ton retour en tout cas. Je me rend compte que l'exemple du readme est pas super clair. 
Je vais le mettre à jour.

**Comment by ScreamZ** [comment]
Super retour,

merci :) et c'est avec plaisir
