### ISSUE TITLE
Booking/Doctrine Persist

### ISSUE THREAD

**Issue by jotamolas** [gmorel/StateWorkflowBundle#3]
Hi Guillerme, i am learning your Bundle, and i find it interesting. 
I have one simple question, in the example and demo bundle, you have two entitys Booking 
(one respect to doctrine, and other that implement all the methods from the services ).
 When i create a booking object, i called a booking not doctrine entity, then, how to persist doctrine class ?

**Comment by gmorel** [comment]
Sorry for the delay.

I notice my example is kinda misleading. It was made from a poor attempt to implement some Domain Driven Design (DDD) principles. 
The aim was to basically split 
- the code really important ([Domain](https://github.com/gmorel/StateWorkflowDemo/blob/master/src/BookingEngine/Domain/Entity/Booking.php)): The workflow logic
- from code less important ([Infra](https://github.com/gmorel/StateWorkflowDemo/blob/master/src/BookingEngine/Infra/DoctrineEntity/Booking.php)): simple getter/setter

![screenshot from 2016-05-31 22 36 42](https://cloud.githubusercontent.com/assets/2279794/15689705/8a8fa3ee-2780-11e6-9117-8e12aea0a532.png)

You can (and should) simply put everything into only one Entity. Basically your doctrine Entity.

![screenshot from 2016-05-31 22 45 06](https://cloud.githubusercontent.com/assets/2279794/15689912/5fd7c496-2781-11e6-8752-9023673ff7a1.png)

I hope this is clearer.

Cheers

**Comment by jotamolas** [comment]
Guillerme thank you!
Your bundle has helped me to unlock my project
In my project, i want persist one entity that saved a lot of workflows to manage  formalities. This entity be like your statemanager class... But as this entity is abstract should implement other entities that extend 
... example: <entity>Workflow (doctrine entity) and <entity>WorkflowAbsence (simple entity that extends Workflow entity and implement all the states methods).
I found a solution for my implementation, first i generate an object of workflowabsence and then casts this object to parent class (workflow). That way i can persist.

Regards!!
